package com.HFA.app.entidad;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Droga generated by hbm2java
 */
@Entity
@Table(name = "droga", catalog = "hovland_db")
public class Droga implements java.io.Serializable {

	private Integer id;
	private Proveedor proveedor;
	private String nombre;
	private String psicoactivo;
	private Boolean legalidad;
	private Float precioGramo;
	private Set<Pedido> pedidos = new HashSet<Pedido>(0);
	private Set<Proveedor> proveedors = new HashSet<Proveedor>(0);

	public Droga() {
	}

	public Droga(Proveedor proveedor, String nombre, String psicoactivo, Boolean legalidad, Float precioGramo,
			Set<Pedido> pedidos, Set<Proveedor> proveedors) {
		this.proveedor = proveedor;
		this.nombre = nombre;
		this.psicoactivo = psicoactivo;
		this.legalidad = legalidad;
		this.precioGramo = precioGramo;
		this.pedidos = pedidos;
		this.proveedors = proveedors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "proveedor")
	public Proveedor getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(Proveedor proveedor) {
		this.proveedor = proveedor;
	}

	@Column(name = "nombre", length = 20)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "psicoactivo", length = 30)
	public String getPsicoactivo() {
		return this.psicoactivo;
	}

	public void setPsicoactivo(String psicoactivo) {
		this.psicoactivo = psicoactivo;
	}

	@Column(name = "legalidad")
	public Boolean getLegalidad() {
		return this.legalidad;
	}

	public void setLegalidad(Boolean legalidad) {
		this.legalidad = legalidad;
	}

	@Column(name = "precioGramo", precision = 12, scale = 0)
	public Float getPrecioGramo() {
		return this.precioGramo;
	}

	public void setPrecioGramo(Float precioGramo) {
		this.precioGramo = precioGramo;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "droga")
	public Set<Pedido> getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set<Pedido> pedidos) {
		this.pedidos = pedidos;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "droga_has_proveedor", catalog = "hovland_db", joinColumns = {
			@JoinColumn(name = "droga_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "proveedor_id", nullable = false, updatable = false) })
	public Set<Proveedor> getProveedors() {
		return this.proveedors;
	}

	public void setProveedors(Set<Proveedor> proveedors) {
		this.proveedors = proveedors;
	}

}
