package com.HFA.app.entidad;
// Generated 25 ene 2022 14:09:33 by Hibernate Tools 5.5.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Droga generated by hbm2java
 */
public class Droga implements java.io.Serializable {

	private Integer id;
	private Proveedor proveedor;
	private String nombre;
	private String psicoactivo;
	private Boolean legalidad;
	private Float precioGramo;
	private Set pedidos = new HashSet(0);
	private Set proveedors = new HashSet(0);

	public Droga() {
	}

	public Droga(Proveedor proveedor, String nombre, String psicoactivo, Boolean legalidad, Float precioGramo,
			Set pedidos, Set proveedors) {
		this.proveedor = proveedor;
		this.nombre = nombre;
		this.psicoactivo = psicoactivo;
		this.legalidad = legalidad;
		this.precioGramo = precioGramo;
		this.pedidos = pedidos;
		this.proveedors = proveedors;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Proveedor getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(Proveedor proveedor) {
		this.proveedor = proveedor;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getPsicoactivo() {
		return this.psicoactivo;
	}

	public void setPsicoactivo(String psicoactivo) {
		this.psicoactivo = psicoactivo;
	}

	public Boolean getLegalidad() {
		return this.legalidad;
	}

	public void setLegalidad(Boolean legalidad) {
		this.legalidad = legalidad;
	}

	public Float getPrecioGramo() {
		return this.precioGramo;
	}

	public void setPrecioGramo(Float precioGramo) {
		this.precioGramo = precioGramo;
	}

	public Set getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set pedidos) {
		this.pedidos = pedidos;
	}

	public Set getProveedors() {
		return this.proveedors;
	}

	public void setProveedors(Set proveedors) {
		this.proveedors = proveedors;
	}

}
