package com.HFA.app.entidad;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Pedido generated by hbm2java
 */
@Entity
@Table(name = "pedido", catalog = "hovland_db")
public class Pedido implements java.io.Serializable {

	private Integer idPedido;
	private Cliente cliente;
	private Droga droga;
	private Proveedor proveedor;
	private Long cantidad;
	private Long precio;

	public Pedido() {
	}

	public Pedido(Cliente cliente, Droga droga, Proveedor proveedor, Long cantidad, Long precio) {
		this.cliente = cliente;
		this.droga = droga;
		this.proveedor = proveedor;
		this.cantidad = cantidad;
		this.precio = precio;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_pedido", unique = true, nullable = false)
	public Integer getIdPedido() {
		return this.idPedido;
	}

	public void setIdPedido(Integer idPedido) {
		this.idPedido = idPedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cliente")
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_droga")
	public Droga getDroga() {
		return this.droga;
	}

	public void setDroga(Droga droga) {
		this.droga = droga;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_prov")
	public Proveedor getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(Proveedor proveedor) {
		this.proveedor = proveedor;
	}

	@Column(name = "cantidad", precision = 10, scale = 0)
	public Long getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Long cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "precio", precision = 10, scale = 0)
	public Long getPrecio() {
		return this.precio;
	}

	public void setPrecio(Long precio) {
		this.precio = precio;
	}

}
