package com.HFA.app.entidad;
// Generated 25 ene 2022 14:09:33 by Hibernate Tools 5.5.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String localidad;
	private Set drogas = new HashSet(0);
	private Set pedidos = new HashSet(0);
	private Set drogas_1 = new HashSet(0);

	public Proveedor() {
	}

	public Proveedor(String nombre, String localidad, Set drogas, Set pedidos, Set drogas_1) {
		this.nombre = nombre;
		this.localidad = localidad;
		this.drogas = drogas;
		this.pedidos = pedidos;
		this.drogas_1 = drogas_1;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

	public Set getDrogas() {
		return this.drogas;
	}

	public void setDrogas(Set drogas) {
		this.drogas = drogas;
	}

	public Set getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set pedidos) {
		this.pedidos = pedidos;
	}

	public Set getDrogas_1() {
		return this.drogas_1;
	}

	public void setDrogas_1(Set drogas_1) {
		this.drogas_1 = drogas_1;
	}

}
